services:
  - type: web
    name: nib
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: SUPABASE_CONN_STRING
        sync: false
